version: '3.7'

services:
  commands:
    container_name: todo_commands
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_COMMAND_PORT}:${SERVER_COMMAND_PORT}
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mqtt
  listener:
    container_name: todo_listener
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mqtt
      - postgres
  queries:
    container_name: todo_queries
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_QUERIES_PORT}:${SERVER_QUERIES_PORT}
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
  mqtt:
    container_name: eclipse-mosquitto
    image: eclipse-mosquitto:1.6
    networks:
      - webnet
    ports:
      - ${TRANSPORT_PORT}:${TRANSPORT_PORT}
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
  nginx:
    container_name: nginx
    image: nginx:apline
    networks:
      - webnet
    ports: 
      ${NGINX_PORT}:${NGINX_PORT}
    depends_on: 
      -postgres
      -mqtt
      -commands
      -listener
      -queries
networks:
  webnet:
volumes:
  pgdata: